services:
  mongodb:
    image: arm64v8/mongo:8.3-noble
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: